# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Delete old branch saving snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXPIRED_TERM: 10w # first letter of year, month, week and day
          REMOTE_REPO: origin
          TARGET_BRANCH_PREFIX: compose_
          DATE_FORMAT: '%Y%m%d'
        run: |
          expired_date=`date -v-$EXPIRED_TERM "+${DATE_FORMAT}"` 
          git fetch --all
          git branch -r | grep "[^* ]+" -Eo | grep "${REMOTE_REPO}/${TARGET_BRANCH_PREFIX}.+" -Eo |
          while read branch; do
            commit_date=`git show -s $branch --format='%cd' --date=format:"${DATE_FORMAT}"`
            if [[ $commit_date -le $expired_date ]]; then
              short_branch=`echo $branch | sed "s/${REMOTE_REPO}\///g"`
              git push ${REMOTE_REPO} --delete $short_branch
            fi 
          done
